import './globals.css'
import { Inter, Roboto} from 'next/font/google'
import {ThemeProvider} from "../providers/theme";
import {AuthProvider} from "../providers/auth";
import {NotificationProvider} from "../providers/notification";

const inter = Inter({ weight: '400', subsets: ['latin'] })
const roboto = Roboto({ weight: '300', subsets: ['latin'] })

export const metadata = {
  title: 'Warehouse 仓储管理系统',
  description: 'Generated by next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <body className={inter.className} suppressHydrationWarning={true}>
        <ThemeProvider>
          <AuthProvider>
            <NotificationProvider>
              {children}
            </NotificationProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
